### ISSUE TITLE
怎么登陆？？

### ISSUE THREAD

**Issue by MIkeeJY** [RedrockTeam/Date_Android#6]

**Comment by Jude95** [comment]
接口跪了。登不上

**Comment by MIkeeJY** [comment]
好吧。。这MVP的架子还是不错的，但是登录的那个软键盘监听也没写。。。弹上去 下来logo都没了

**Comment by Lich2013** [comment]
接口没跪, 我只是换了点东西, 8001端口换成 `lich2013.com/date/balabala`
